// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using SeleniumExtras.WaitHelpers;

namespace Ditec.Teste_de_Interface.ST01Funcionarios
{
   [TestFixture]
   public class CT05ExclusaoDeCadastroExistenteTest
   {
      private IWebDriver driver;
      public IDictionary<string, object> vars { get; private set; }
      private IJavaScriptExecutor js;
      private WebDriverWait timespan; 

      [SetUp]
      public void SetUp()
      {
         driver = new ChromeDriver();
         js = (IJavaScriptExecutor)driver;
         vars = new Dictionary<string, object>();
         timespan = new WebDriverWait(driver, TimeSpan.FromSeconds(2));
      }

		[TearDown]
		protected void TearDown()
		{
			driver.Quit();
		}

		[Test]
      public void cT05ExclusaoDeCadastroExistente()
      {
         driver.Navigate().GoToUrl("https://admin.ditecdistribuidora.com.br/");
         driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
         driver.FindElement(By.Id("Usuario")).Click();
         driver.FindElement(By.Id("Usuario")).SendKeys("suporte@forsh.com.br");
         driver.FindElement(By.Id("Senha")).SendKeys("1234");
         driver.FindElement(By.CssSelector(".btn")).Click();

         timespan.Until(ExpectedConditions.ElementExists(By.LinkText("Dashboard Admin"))).Click();
         timespan.Until(ExpectedConditions.ElementExists(By.LinkText("Distribuidoras"))).Click();
         timespan.Until(ExpectedConditions.ElementExists(By.LinkText("Funcionários"))).Click();
         IWebElement search = timespan.Until(ExpectedConditions.ElementExists(By.CssSelector("#iptSearch")));
         search.Click();

         string email = "raphael.mota14@hotmail.com";

         for (int i = 0; i < email.Length; i++)
         {
            search.SendKeys(email[i].ToString());
            Thread.Sleep(10);
         }

			var button1 = driver.FindElement(By.CssSelector("button#btnSearch > i[class='fa fa-search']"));
         button1.Click();

         timespan.Until(ExpectedConditions.ElementExists((By.CssSelector(".btn.btn-sm.btn-danger")))).Click();
         IWebElement confirmButton = timespan.Until(ExpectedConditions.ElementToBeClickable(By.XPath("//button[contains(text(), 'Sim')]")));
         confirmButton.Click();
         search.Clear();
         driver.Navigate().Refresh(); 
         bool assertion = (driver.PageSource.Contains(email));
         Assert.That(!assertion);

         //driver.FindElement(By.CssSelector(".sweet-confirm")).Click();
         //Assert.That(driver.FindElement(By.CssSelector(".toast-message")).Text, Is.EqualTo("Registro excluido com sucesso!"));
      }
   }
}
