// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Ditec.Teste_de_Interface.ST01Funcionarios
{
   [TestFixture]
   public class CT01CadastroDeProdutosEmBrancoTest
   {
      private IWebDriver driver;
      public IDictionary<string, object> vars { get; private set; }
      private IJavaScriptExecutor js;
      [SetUp]
      public void SetUp()
      {
         driver = new ChromeDriver();
         js = (IJavaScriptExecutor)driver;
         vars = new Dictionary<string, object>();
      }
      [TearDown]
      protected void TearDown()
      {
         driver.Quit();
      }
      [Test]
      public void cT01CadastroDeProdutosEmBranco()
      {
         driver.Navigate().GoToUrl("https://admin.ditecdistribuidora.com.br/");
         driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
         driver.FindElement(By.Id("Usuario")).SendKeys("suporte@forsh.com.br");
         driver.FindElement(By.Id("Senha")).SendKeys("1234");
         driver.FindElement(By.CssSelector(".btn")).Click();
         driver.FindElement(By.LinkText("Dashboard Admin")).Click();
         driver.FindElement(By.LinkText("Produtos")).Click();
         driver.FindElement(By.CssSelector(".in > li:nth-child(3) > a")).Click();
         driver.FindElement(By.CssSelector(".btn-info")).Click();
         driver.FindElement(By.CssSelector(".btn-success")).Click();
         Assert.That(driver.FindElement(By.CssSelector(".alert-danger")).Text, Is.EqualTo("×\\\\nVerifique os dados informados."));
         Assert.That(driver.FindElement(By.CssSelector(".form-group:nth-child(2) .field-validation-error")).Text, Is.EqualTo("Nome é obrigatório"));
         {
            var element = driver.FindElement(By.CssSelector(".note-icon-question"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
         }
         {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
         }
         Assert.That(driver.FindElement(By.CssSelector(".form-group:nth-child(4) .field-validation-error")).Text, Is.EqualTo("Unidade é obrigatório"));
         Assert.That(driver.FindElement(By.CssSelector(".form-group:nth-child(5) .field-validation-error")).Text, Is.EqualTo("Fabricante é obrigatório"));
         Assert.That(driver.PageSource.Contains("Grupo de produto é obrigatório"));
         Assert.That(driver.PageSource.Contains("Peso é obrigatório"));
         Assert.That(driver.PageSource.Contains("Comprimento é obrigatório"));
         Assert.That(driver.PageSource.Contains("Largura é obrigatório"));
         Assert.That(driver.PageSource.Contains("Altura é obrigatório"));


      }
   }

}
