// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Liven
{

   [TestFixture]
   public class CT01FreteExpressoAlterandoParaEconomicoTest
   {
      private IWebDriver driver;
      public IDictionary<string, object> vars { get; private set; }
      private IJavaScriptExecutor js;
      [SetUp]
      public void SetUp()
      {
         driver = new ChromeDriver();
         js = (IJavaScriptExecutor)driver;
         vars = new Dictionary<string, object>();
      }
      [TearDown]
      protected void TearDown()
      {
         driver.Quit();
      }
      [Test]
      public void cT01FreteExpressoAlterandoParaEconomico()
      {
         driver.Navigate().GoToUrl("https://livencasa.com/");
         driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
         {
            var element = driver.FindElement(By.CssSelector(".hidden-xs > #cart .fa"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
         }
         {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
         }
         Thread.Sleep(10000);
         driver.FindElement(By.CssSelector(".account span")).Click();
         driver.FindElement(By.Id("input-login-email")).Click();
         driver.FindElement(By.Id("input-login-email")).SendKeys("suporte@forsh.com.br");
         driver.FindElement(By.CssSelector(".input-group-addon:nth-child(4) > .btn")).Click();
         Thread.Sleep(10000);
         driver.FindElement(By.Id("input-login-senha")).Click();
         driver.FindElement(By.Id("input-login-senha")).SendKeys("adm@forsh");

         Thread.Sleep(10000);
         driver.Navigate().GoToUrl("https://livencasa.com/carrinho");
         {
            var element = driver.FindElement(By.LinkText("Finalizar Compra"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
         }
         driver.FindElement(By.Id("input-postcode")).Click();
         driver.FindElement(By.Id("input-postcode")).SendKeys("74922-740");
         Thread.Sleep(10000);
         driver.FindElement(By.Id("button-quote")).Click();
         {
            var element = driver.FindElement(By.Id("button-quote"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element).Perform();
            Thread.Sleep(10000);
         }
         {
            var element = driver.FindElement(By.TagName("body"));
            Actions builder = new Actions(driver);
            builder.MoveToElement(element, 0, 0).Perform();
            Thread.Sleep(10000);
         }
         driver.FindElement(By.CssSelector("label:nth-child(2) span")).Click();
         driver.FindElement(By.LinkText("Finalizar Compra")).Click();
         Thread.Sleep(10000);
         Assert.That(driver.FindElement(By.CssSelector("tr:nth-child(2) strong")).Text, Is.EqualTo("Expresso:"));
      }
   }

}
