// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
using System.Text.RegularExpressions;
using OpenQA.Selenium.Support.Extensions;

namespace Suplemento
{
    [TestFixture]
    public class CT01CadastroSubGrupoProdutosTest
    {
        private ChromeDriver driver;
        public IDictionary<string, object> vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new ChromeDriver();

            js = (IJavaScriptExecutor)driver;
            vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void cT01CadastroSubGrupoProdutos()


        {



            driver.Navigate().GoToUrl("https://admin.suplementonutricaoanimal.com.br/");

            driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
            driver.FindElement(By.Id("Usuario")).Click();
            driver.FindElement(By.Id("Usuario")).SendKeys("suporte@forsh.com.br");
            driver.FindElement(By.Id("Senha")).Click();
            driver.FindElement(By.Id("Senha")).SendKeys("adm@forsh11");
            driver.FindElement(By.CssSelector(".btn")).Click();
            driver.FindElement(By.LinkText("Dashboard Admin")).Click();
            driver.FindElement(By.LinkText("Produtos")).Click();
            Thread.Sleep(5000);
            driver.FindElement(By.LinkText("Grupos")).Click();
            Thread.Sleep(5000);
            driver.FindElement(By.Id("iptSearch")).Click();
            driver.FindElement(By.Id("iptSearch")).SendKeys("teste");
            Thread.Sleep(5000);
            driver.FindElement(By.CssSelector(".odd:nth-child(1) .btn-primary > .fa")).Click();
            Thread.Sleep(5000);
            var codigoErp = driver.FindElement(By.Id("CodigoERP")).GetAttribute("value");
            var mensagemDeErroEsperada = driver.PageSource.Contains("Codigo ERP não pode estar vazio");

            driver.FindElement(By.CssSelector(".btn-success")).Click();

            if (codigoErp.Contains(""))
            {
                 
                 
                    Console.WriteLine("Código ERP Vazio não tratado");
                    Assert.AreEqual("Codigo ERP não pode estar vazio", mensagemDeErroEsperada);
                driver.TakeScreenshot().SaveAsFile("error", ScreenshotImageFormat.Png);
                
            }
            else
            {

                Thread.Sleep(5000);

                driver.FindElement(By.Id("Nome")).Click();
                Thread.Sleep(10000);
                driver.FindElement(By.Id("Nome")).SendKeys("teste");
                Thread.Sleep(10000);
                driver.FindElement(By.CssSelector(".btn-success")).Click();

            }

        }
    }
}
