// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace Suplemento
{

   [TestFixture]
   public class UntitledTest
   {
      private IWebDriver driver;
      public IDictionary<string, object> vars { get; private set; }
      private IJavaScriptExecutor js;
      [SetUp]
      public void SetUp()
      {
         driver = new ChromeDriver();
         js = (IJavaScriptExecutor)driver;
         vars = new Dictionary<string, object>();
      }
      [TearDown]
      protected void TearDown()
      {
         driver.Quit();
      }
      [Test]
      public void untitled()
      {
         driver.Navigate().GoToUrl("https://admin.suplementonutricaoanimal.com.br/");
         driver.Manage().Window.Size = new System.Drawing.Size(1936, 1056);
         driver.FindElement(By.Id("Usuario")).Click();
         driver.FindElement(By.Id("Usuario")).SendKeys("suporte@forsh.com.br");
         driver.FindElement(By.Id("Senha")).SendKeys("adm@forsh11");
         driver.FindElement(By.CssSelector(".btn")).Click();
         driver.FindElement(By.LinkText("Dashboard Admin")).Click();
         driver.FindElement(By.LinkText("Produtos")).Click();
         driver.FindElement(By.CssSelector(".nav-second-level > li:nth-child(4) > a")).Click();
         driver.FindElement(By.CssSelector(".btn-info")).Click();
         vars["codigoERP"] = driver.FindElement(By.Id("CodigoERP")).GetAttribute("value");
         vars["Nome"] = driver.FindElement(By.Id("Nome")).GetAttribute("value");
         vars["Fabricante"] = driver.FindElement(By.Id("Fabricante")).GetAttribute("value");
         js.ExecuteScript("window.scrollTo(0,539)");
         driver.FindElement(By.CssSelector(".btn-success")).Click();
         Assert.That(driver.FindElement(By.CssSelector(".field-validation-error:nth-child(3)")).Text, Is.EqualTo("Informe código do produto do ERP."));
         Assert.That(driver.FindElement(By.CssSelector(".form-group:nth-child(2) .field-validation-error")).Text, Is.EqualTo("Nome é obrigatório"));
         Assert.That(driver.FindElement(By.CssSelector(".form-group:nth-child(5) .field-validation-error")).Text, Is.EqualTo("Fabricante é obrigatório"));
         Assert.That(driver.FindElement(By.CssSelector(".alert-danger")).Text, Is.EqualTo("×\\\\nVerifique os dados informados."));
      }
   }

}
